[providers]
node = "18"

[variables]
NODE_ENV = "production"

[phases.install]
cmds = ["cd backend && npm ci"]

[phases.build]
dependsOn = ["install"]
cmds = ["cd backend && echo 'Build completed'"]

[start]
cmd = "cd backend && npm start"